language: python
sudo: required
before_install:
# cancel this build if there is another older build running
- gem install travis
- travis whoami --org

script:
# deployment

after_script:
# restart newest cancelled build newer than this
