sudo: required

language: go
go:
- "1.10"

env:
  global:
    - ONEBUILD_BRANCHES=master,staging
    - N=6

before_install:
# any failed command here fails the build immediately.
# cancel this build if there is another older build running
# maybe retry after 30 seconds
- go install ./onebuild
- onebuild start

# default install: `go get -t ./...`
# default script: `make` (if Makefile) or `go test -v ./...`

script:
- sleep 120

after_script:
- onebuild finish
