sudo: required

language: go
go:
- "1.10"

before_install:
# any failed command here fails the build immediately.
# cancel this build if there is another older build running
# maybe retry after 30 seconds
- go get -u ./travisserializer
- travisserializer start

# default install: `go get -t ./...`
# default script: `make` (if Makefile) or `go test -v ./...`

script:
- sleep 300

after_script:
- travisserializer finish
